# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_test.ipynb.

# %% auto 0
__all__ = ['test']

# %% ../nbs/03_test.ipynb 3
def test():
    print("Test nbdev")

# %% ../nbs/03_test.ipynb 24
def test():
    print("Test nbdev 2")
